import { Episode, Program } from './types';

export const initialPrograms: Program[] = [
  { id: 'PROG001', name: 'Hub Techcast', description: 'Podcast de tecnologia', presenter: 'Marina Silva', director: 'Carlos Mendes', platform: 'YouTube / Spotify' },
  { id: 'PROG002', name: 'Papo de Mercado', description: 'Entrevistas sobre negócios e mercado', presenter: 'Roberto Justus', director: 'Fernanda Lima', platform: 'Instagram' },
  { id: 'PROG003', name: 'Creators em Foco', description: 'Dicas para criadores de conteúdo', presenter: 'João', director: 'Carlos Mendes', platform: 'YouTube' },
];

export const initialData: Episode[] = [
  {
    id: 'EP001',
    status: 'PUBLICADO',
    program: 'Hub Techcast',
    episode: 'S02E01',
    theme: 'Inteligência Artificial no Dia a Dia',
    presenter: 'Marina Silva',
    director: 'Carlos Mendes',
    script: '10/10/2023',
    recording: '15/10/2023',
    editing: '18/10/2023',
    thumbnail: 'Pronta',
    approval: '20/10/2023',
    publication: '22/10/2023',
    airDate: '24/10/2023',
    time: '19:00',
    platform: 'YouTube / Spotify',
    responsible: 'Ana Costa',
    priority: 'ALTA',
    duration: '45:00',
    notes: 'Temporada de estréia com patrocínio master.',
    progress: 100,
  },
  {
    id: 'EP002',
    status: 'REVISÃO',
    program: 'Hub Techcast',
    episode: 'S02E02',
    theme: 'O Futuro do Trabalho Remoto',
    presenter: 'Marina Silva',
    director: 'Carlos Mendes',
    script: '12/10/2023',
    recording: '17/10/2023',
    editing: '21/10/2023',
    thumbnail: 'Pronta',
    approval: 'Pendente',
    publication: '29/10/2023',
    airDate: '31/10/2023',
    time: '19:00',
    platform: 'YouTube / Spotify',
    responsible: 'João Marcos',
    priority: 'MÉDIA',
    duration: '52:10',
    notes: 'Revisar áudio do convidado no minuto 15.',
    progress: 85,
  },
  {
    id: 'EP003',
    status: 'ATRASADO',
    program: 'Papo de Mercado',
    episode: 'S01E15',
    theme: 'Tendências do E-commerce 2024',
    presenter: 'Roberto Justus',
    director: 'Fernanda Lima',
    script: '01/10/2023',
    recording: '05/10/2023',
    editing: 'Atrasada',
    thumbnail: 'Pendente',
    approval: '-',
    publication: '-',
    airDate: '15/10/2023',
    time: '20:00',
    platform: 'Instagram / YouTube',
    responsible: 'Pedro Alves',
    priority: 'ALTA',
    duration: '60:00',
    notes: 'Convidado cancelou e reagendou. Prazo estourado.',
    progress: 40,
  },
  {
    id: 'EP004',
    status: 'EDIÇÃO',
    program: 'Creators em Foco',
    episode: 'S03E05',
    theme: 'Como monetizar cortes no TikTok',
    presenter: 'Felipe Neto',
    director: 'Tiago Leifert',
    script: '14/10/2023',
    recording: '19/10/2023',
    editing: 'Em andamento',
    thumbnail: 'Pronta',
    approval: '-',
    publication: '-',
    airDate: '26/10/2023',
    time: '18:00',
    platform: 'TikTok / Shorts',
    responsible: 'Maria Eduarda',
    priority: 'BAIXA',
    duration: '15:00',
    notes: 'Gerar 5 cortes extras pro Reels.',
    progress: 60,
  },
  {
    id: 'EP005',
    status: 'PRODUÇÃO',
    program: 'Papo de Mercado',
    episode: 'S01E16',
    theme: 'Startups Bootstrapped',
    presenter: 'Roberto Justus',
    director: 'Fernanda Lima',
    script: '20/10/2023',
    recording: 'Hoje, 14h',
    editing: '-',
    thumbnail: 'Ideando',
    approval: '-',
    publication: '-',
    airDate: '02/11/2023',
    time: '20:00',
    platform: 'Instagram / YouTube',
    responsible: 'Lucas Gomes',
    priority: 'MÉDIA',
    duration: '40:00',
    notes: 'Estúdio B reservado.',
    progress: 30,
  },
  {
    id: 'EP006',
    status: 'ROTEIRO',
    program: 'Hub Techcast',
    episode: 'S02E03',
    theme: 'Cripto para Iniciantes',
    presenter: 'Marina Silva',
    director: 'Carlos Mendes',
    script: 'Em revisão',
    recording: '25/10/2023',
    editing: '-',
    thumbnail: '-',
    approval: '-',
    publication: '-',
    airDate: '07/11/2023',
    time: '19:00',
    platform: 'YouTube / Spotify',
    responsible: 'Ana Costa',
    priority: 'ALTA',
    duration: '50:00',
    notes: 'Aguardando validação jurídica do roteiro.',
    progress: 15,
  },
  {
    id: 'EP007',
    status: 'IDEIA',
    program: 'Creators em Foco',
    episode: 'S03E06',
    theme: 'Agenciamento de Influenciadores',
    presenter: 'Felipe Neto',
    director: 'Tiago Leifert',
    script: '-',
    recording: '-',
    editing: '-',
    thumbnail: '-',
    approval: '-',
    publication: '-',
    airDate: 'Em aberto',
    time: '18:00',
    platform: 'TikTok / Shorts',
    responsible: 'Maria Eduarda',
    priority: 'BAIXA',
    duration: '15:00',
    notes: 'Buscar convidados de agências pequenas.',
    progress: 5,
  }
];
